# Generated by Django 5.0.6 on 2024-05-15 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inimigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('vida', models.IntegerField()),
                ('dano', models.IntegerField()),
                ('armadura', models.IntegerField()),
                ('descricao', models.TextField()),
                ('recompensas_ouro', models.IntegerField(default=0)),
                ('recompensas_exp', models.IntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='inimigos/')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('efeito', models.CharField(max_length=255)),
                ('imagem_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('vida', models.IntegerField()),
                ('dano', models.IntegerField()),
                ('armadura', models.IntegerField()),
                ('experiencia', models.IntegerField(default=0)),
                ('nivel', models.IntegerField(default=1)),
                ('imagem_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Combate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('venceu', 'Venceu'), ('perdeu', 'Perdeu')], max_length=10)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates', to=settings.AUTH_USER_MODEL)),
                ('inimigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates', to='jogoRPG.inimigo')),
            ],
        ),
    ]
