# Generated by Django 5.0.6 on 2024-05-16 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogoRPG', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassePersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('habilidade_especial', models.CharField(max_length=255)),
                ('imagem_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inimigo',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='imagem_url',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='username',
        ),
        migrations.AddField(
            model_name='inimigo',
            name='imagem_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='inimigo',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jogador',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogador',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jogoRPG.classepersonagem'),
        ),
    ]
