# Generated by Django 5.0.6 on 2024-05-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogoRPG', '0002_classepersonagem_remove_inimigo_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jogador',
            name='armadura',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='dano',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='vida',
            field=models.IntegerField(default=100),
        ),
    ]
