# Generated by Django 5.0.6 on 2024-05-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogoRPG', '0003_jogador_nome_alter_jogador_armadura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='armadura',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='dano',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='vida',
        ),
        migrations.AddField(
            model_name='classepersonagem',
            name='armadura',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='classepersonagem',
            name='dano',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='classepersonagem',
            name='experiencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classepersonagem',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='classepersonagem',
            name='vida',
            field=models.IntegerField(default=100),
        ),
    ]
