# Generated by Django 5.0.6 on 2024-05-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogoRPG', '0004_remove_jogador_armadura_remove_jogador_dano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classepersonagem',
            name='imagem_url',
            field=models.ImageField(blank=True, upload_to='imagens/classe/'),
        ),
    ]
